name: nitrokey-app
# version format: <app version>snap<snapcraft.yaml major revision>
version: 1.0snap2
summary: Nitrokey Application
description: A QT GUI for managing your Nitrokey device
confinement: strict
#confinement: devmode

apps:
  nitrokey-app:
    command: desktop-launch "nitrokey-app -style fusion" 2>/dev/null >/dev/null
    plugs:
      - platform
      - unity7
      - opengl
      - home
      - x11
      - gsettings
      - network
      - network-bind
      - mount-observe
  dev:
    command: desktop-launch "nitrokey-app.debug -style fusion"
    plugs:
      - platform
      - unity7
      - opengl
      - home
      - x11
      - gsettings
      - network
      - network-bind
      - mount-observe
  no-plugs:
    command: qt5-launch nitrokey-app -style fusion

plugs:
    platform: # plug name, to be used later
        interface: content
        content: ubuntu-app-platform1 # content being mounted and the version, currently 1
        target: ubuntu-app-platform # the mount directory created
        default-provider: ubuntu-app-platform # default content source snap, currently the only provider too

parts:
  application:
    plugin: cmake
    source: git://github.com/Nitrokey/nitrokey-app.git
    source-branch: master
    stage-packages:
      # Here for the plugins-- they're not linked in automatically.
      - libqt5gui5
    after: [desktop-ubuntu-app-platform]
    prime: [ubuntu-app-platform]
    build-attributes: [no-system-libraries]
    #after: [desktop-qt5] # A wiki part
    #after: [qt5conf] # A wiki part
